apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: nginx-logs
        - name: filebeat-config
          configMap:
            name: filebeat-configmap
            items:
              - key: filebeat.yml
                path: filebeat.yml
      containers:
      - name: pm-backend-container
        image: jishnuvk/spe-main-project:back_end_latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8082
        volumeMounts:
            - name: nginx-logs
              mountPath: /app/logs/
        env:
        - name: DB_SERVER
          value: db-service
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
                name: db-secret
                key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-db

      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.5.0
        volumeMounts:
          - name: nginx-logs
            mountPath: /usr/share/filebeat/var/log/app/
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml  
            


---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - var/log/app/*.log

    output.logstash:
      hosts: ["logstash-logstash:5044"]
