apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-root-password: cGxhY2UtbWFuLXJvb3QtUGFzc3dvcmQ=
  mysql-username: cGxhY2VtZW50dXNlcg==
  mysql-password: cGFzc2FuZHdvcmQ=