version: '3'
services:

  placement-manager-db:
    image: mysql:8.0.28
    container_name: pm-db-container
    volumes:
      - db-data:/var/lib/mysql/
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=place-man-root-Password
      - MYSQL_USER=placementuser
      - MYSQL_PASSWORD=passandword
      - MYSQL_DATABASE=placement_manager
    networks:
      - db
    restart: on-failure

  placement-manager-backend:
    image: karthikhegde2022/placement-manager-backend
    container_name: pm-backend-container
    environment:
      - DB_SERVER=placement-manager-db
      - DB_NAME=placement_manager
      - MYSQL_USER=placementuser
      - MYSQL_PASSWORD=passandword
    ports:
      - 8082:8082
    depends_on:
      - placement-manager-db
    networks:
      - db
      - frontend
    restart: on-failure

  placement-manager-frontend:
    image: karthikhegde2022/placement-manager-frontend
    container_name: pm-frontend-container
    ports:
      - 4200:80
    depends_on:
      - placement-manager-backend
    networks:
      - frontend
    restart: on-failure

volumes:
  db-data:
  
networks:
  db:
  frontend:
  
