- name: copy docker-compose yaml file to remote machine and run it
  hosts: virtualmachine
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: copy docker-compose yaml file to remote machine
      copy:
        src: ./playbook.yml
        dest: ~/

    - name: run docker-compose up 
      docker_compose:
        project_src: ~/
        state: present
        
