

name: CI/CD

on:

  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]


  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
#       - name: Build Maven
#         run: |
#           cd backend/placementmanager/
#           mvn clean install
#       - name: Docker build
#         run: |
          
