

name: CI/CD

on:

  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]


  workflow_dispatch:

env:

  BACKEND_IMAGE: spe-main-project:back_end
  FRONTEND_IMAGE: spe-main-project:front_end

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build Number
        uses: travisj/build-number-action@v1.0.2
        id: build-number
        with:
          key: placementmanager

      - name: Build Maven
        run: |
          cd backend/placementmanager/
          mvn clean install
     
      - name: Docker build backend
        run: |
          cd backend/
          docker build -t $BUILD_NUMBER .
        env:
          BUILD_NUMBER: ${{secrets.DOCKERHUB_USERNAME}}/${{ env.BACKEND_IMAGE }}_latest

      - name: Docker build frontend

        run: |
          cd frontend/
          docker build -t $BUILD_NUMBER .
        env:
          BUILD_NUMBER:  ${{secrets.DOCKERHUB_USERNAME}}/${{ env.FRONTEND_IMAGE }}_latest
        # ${{ env.FRONTEND_IMAGE }}_${{ steps.build-number.outputs.build-number}}  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push images
        run: |
          docker push $FRONTEND_IMAGE
          docker push $BACKEND_IMAGE
        env:
          FRONTEND_IMAGE: ${{secrets.DOCKERHUB_USERNAME}}/${{ env.FRONTEND_IMAGE }}_latest
          BACKEND_IMAGE: ${{secrets.DOCKERHUB_USERNAME}}/${{ env.BACKEND_IMAGE }}_latest




